Build: Only run pre-commit checks if node found
In some IDEs, or Git GUIs, the i18nlint and eslint checks will fail
because of PATH being set incorrectly.

Let's exit early (sucessfully) if we can't find `node`.

diff --git a/bin/pre-commit b/bin/pre-commit
--- a/bin/pre-commit
+++ b/bin/pre-commit
@@ -2,6 +2,11 @@
 
 echo "\nBy contributing to this project, you license the materials you contribute under the GNU General Public License v2 (or later).\n\n"
 
+if ! $(command -v node >/dev/null 2>&1); then
+	echo "\nnode not found in PATH. Skipping checks…\n"
+	exit 0
+fi
+
 files=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx*$")
 if [ "$files" = "" ]; then
     exit 0
